<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE Products [
	<!ELEMENT Products (type,price,numberProducts,components?)>
	<!ATTLIST Products name CDATA #REQUIRED>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT numberProducts (#PCDATA)>
	<!ELEMENT components (component+)>
	<!ELEMENT component (name,price, supplier, numberComponents)>
	<!ATTLIST component id CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>				
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT supplier (#PCDATA)>
	<!ELEMENT numberComponents (#PCDATA)>
]>

<Products name="proxamol">
    <type>anti-inflammatory</type>
    <price>9.74</price>
    <numberProducts>100</numberProducts>
    <components>
        <component id="1">
            <name>Serenoa</name>
            <price>20.0</price>
            <supplier>Atienza</supplier>
            <numberComponents>200</numberComponents>
        </component>
    </components>
</Products>
